GO
CREATE DATABASE books_store
GO
use books_store;

CREATE TABLE roles
(
id INT PRIMARY KEY IDENTITY,
name VARCHAR(100) NOT NULL
)

CREATE TABLE users
(
id INT PRIMARY KEY IDENTITY,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role INT FOREIGN KEY REFERENCES roles(id)
)

CREATE TABLE logs
(
id INT PRIMARY KEY IDENTITY,
user_id INT NOT NULL FOREIGN KEY REFERENCES users(id),
message VARCHAR(300) NOT NULL
)

CREATE TABLE genres
(
id INT PRIMARY KEY IDENTITY,
name VARCHAR(100) NOT NULL
)

CREATE TABLE books
(
id INT PRIMARY KEY IDENTITY,
name VARCHAR(150) NOT NULL,
price INT NOT NULL,
description VARCHAR(500) NOT NULL,
pages INT NOT NULL,
year_of_publishing INT NOT NULL,
isbn VARCHAR(13) NOT NULL,
genre_id INT NOT NULL FOREIGN KEY REFERENCES genres(id),
amount INT NOT NULL,
status VARCHAR(100) NOT NULL DEFAULT 'In stock'
)

CREATE TABLE carts
(
id INT PRIMARY KEY IDENTITY,
user_id INT NOT NULL UNIQUE FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE
)

CREATE TABLE book_images
(
id INT PRIMARY KEY IDENTITY,
book_id INT NOT NULL FOREIGN KEY REFERENCES books(id) ON DELETE CASCADE,
url VARCHAR(300) NOT NULL
)

CREATE TABLE reviews
(
id INT PRIMARY KEY IDENTITY,
book_id INT NOT NULL FOREIGN KEY REFERENCES books(id) ON DELETE CASCADE,
user_id INT NOT NULL FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,
review VARCHAR(300) NOT NULL
)

CREATE TABLE authors
(
id INT PRIMARY KEY IDENTITY,
name VARCHAR(150) NOT NULL,
date_of_birth date NOT NULL,
biography VARCHAR(500) NOT NULL,
)

CREATE TABLE authors_books
(
id INT PRIMARY KEY IDENTITY,
author_id INT NOT NULL FOREIGN KEY REFERENCES authors(id) ON DELETE CASCADE,
book_id INT NOT NULL FOREIGN KEY REFERENCES books(id) ON DELETE CASCADE
)

CREATE TABLE books_carts
(
id INT PRIMARY KEY IDENTITY,
book_id INT NOT NULL FOREIGN KEY REFERENCES books(id) ON DELETE CASCADE,
cart_id INT NOT NULL FOREIGN KEY REFERENCES carts(id) ON DELETE CASCADE,
added_date date NOT NULL
)

CREATE TABLE orders
(
id INT PRIMARY KEY IDENTITY,
user_id INT NOT NULL FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,
price INT NOT NULL,
creation_date date NOT NULL
)

CREATE TABLE books_orders
(
id INT PRIMARY KEY IDENTITY,
order_id INT NOT NULL FOREIGN KEY REFERENCES orders(id) ON DELETE CASCADE,
book_id INT NOT NULL FOREIGN KEY REFERENCES books(id) ON DELETE CASCADE,
)